
Running tests... 
----------------------------------------------------------------------
 test_api (unittest.loader._FailedTest) ... ERROR (0.000000)s

======================================================================
ERROR [0.000000s]: test_api (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_api
Traceback (most recent call last):
  File "D:\办公软件\python\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "D:\办公软件\python\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\小米笔记本\Desktop\全篇\testcase\test_api.py", line 2, in <module>
    from common.requests_api import auto_get, auto_post
  File "C:\Users\小米笔记本\Desktop\全篇\common\requests_api.py", line 14, in <module>
    url_head = conf.get('requests_setting', 'url_head')
  File "D:\办公软件\python\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "D:\办公软件\python\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'requests_setting'


----------------------------------------------------------------------
Ran 1 test in 0:00:00

FAILED
 (Errors=1)

Generating HTML reports... 
