
Running tests... 
----------------------------------------------------------------------
 test_001 (test_api.TestBaidu) ... OK (5.129990)s
 test_002 (test_api.TestBaidu) ... OK (5.108796)s
 test_003 (test_api.TestBaidu) ... ERROR (0.000993)s

======================================================================
ERROR [0.000993s]: test_003 (test_api.TestBaidu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\小米笔记本\Desktop\全篇\testcase\test_api.py", line 30, in test_003
    unittest.TestCase.fail()
TypeError: fail() missing 1 required positional argument: 'self'

----------------------------------------------------------------------
Ran 3 tests in 0:00:10

FAILED
 (Errors=1)

Generating HTML reports... 
