2020-07-31 15:04:16.201 | WARNING  | __main__:select_all:63 - SQL语句执行异常，请检查SQL语句:select * from None,异常:(1146, "Table 'testbase.none' doesn't exist")
2020-07-31 15:05:29.187 | WARNING  | __main__:select_one:46 - SQL语句执行异常，请检查SQL语句:select * from None where None = "None",异常:(1146, "Table 'testbase.none' doesn't exist")
2020-07-31 15:05:53.686 | ERROR    | __main__:<module>:75 - An error has been caught in function '<module>', process 'MainProcess' (13944), thread 'MainThread' (460):
Traceback (most recent call last):

> File "C:/Users/小米笔记本/Desktop/全篇/common/base_api.py", line 75, in <module>
    SQL().select_one()
    └ <class '__main__.SQL'>

TypeError: select_one() missing 3 required positional arguments: 'table_name', 'field_name', and 'value_name'
2020-07-31 15:06:23.630 | WARNING  | __main__:select_one:46 - SQL语句执行异常，请检查SQL语句:select * from None where None = "None",异常:(1146, "Table 'testbase.none' doesn't exist")
